name: 打包上传
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: [ 15 ]
    steps:
      - uses: actions/checkout@v3

      - name: 安装nodejs ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - uses: pnpm/action-setup@v3
        name: 安装 pnpm
        with:
            version: 8



      - name: 安装依赖
        run: pnpm install
      - name: 构建
        run: pnpm run build
      - name: 发布到服务器
        uses: easingthemes/ssh-deploy@v5.0.3
        env:
          REMOTE_HOST: ${{ secrets.HOST }}
          REMOTE_USER: ${{ secrets.USER }}
          SSH_PRIVATE_KEY: ${{ secrets.PASS }}
          REMOTE_PORT: ${{ secrets.PORT }}
          SOURCE: "dist/"
          TARGET: ${{ secrets.PATH }}
