name: 打包上传
on:
  push:
    branches:
      - main
jobs:
  cache-and-install:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: 设置 Java:21 环境
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 21

      - name: 设置 Gradle 环境
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-home-cache-cleanup: true

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - uses: pnpm/action-setup@v4
        name: 安装 pnpm
        with:
          version: 8

      - name: 获取 pnpm 存储目录
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV


      - name: 安装npm依赖
        run: |
          pnpm install

      - name: 安装依赖和打包
        run: |
          pnpm run build

      - name: push to server
        uses: easingthemes/ssh-deploy@v5.0.3
        env:
          REMOTE_HOST: ${{ secrets.HOST }}
          REMOTE_USER: ${{ secrets.USER }}
          SSH_PRIVATE_KEY: ${{ secrets.PASS }}
          REMOTE_PORT: ${{ secrets.PORT }}
          SOURCE: "dist/"
          TARGET: ${{ secrets.PATH }}
