name: 打包上传
on:
  push:
    branches:
      - main
jobs:
  cache-and-install:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
#
#      - uses: pnpm/action-setup@v4
#        name: 安装 pnpm
#        with:
#          version: 8
#
#      - name: Install Node.js
#        uses: actions/setup-node@v4
#        with:
#          node-version: 20
#          cache: "pnpm"
#        run: pnpm install --no-frozen-lockfile && pnpm run build

      - name: push to server
        uses: easingthemes/ssh-deploy@v5.0.3
        env:
          REMOTE_HOST: ${{ secrets.HOST }}
          REMOTE_USER: ${{ secrets.USER }}
          SSH_PRIVATE_KEY: ${{ secrets.PASS }}
          REMOTE_PORT: ${{ secrets.PORT }}
          SOURCE: "dist/"
          TARGET: ${{ secrets.PATH }}
