name: 打包上传
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: 安装nodejs
        uses: actions/setup-node@v4.0.2
      - name: 安装依赖
        run: npm run postinstall
      - name: 构建
        run: npm run build
      - name: 发布到服务器
        uses: easingthemes/ssh-deploy@v5.0.3
        env:
          REMOTE_HOST: ${{ secrets.HOST }}
          REMOTE_USER: ${{ secrets.USER }}
          SSH_PRIVATE_KEY: ${{ secrets.PASS }}
          REMOTE_PORT: ${{ secrets.PORT }}
          SOURCE: "dist/"
          TARGET: ${{ secrets.PATH }}
