name: 打包上传
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20]
    steps:
      - uses: actions/checkout@v4

      - name: install nodejs
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: install deps
        run: npm install
      - name: build
        run: npm run build
      - name: push to server
        uses: easingthemes/ssh-deploy@v5.0.3
        env:
          REMOTE_HOST: ${{ secrets.HOST }}
          REMOTE_USER: ${{ secrets.USER }}
          SSH_PRIVATE_KEY: ${{ secrets.PASS }}
          REMOTE_PORT: ${{ secrets.PORT }}
          SOURCE: "dist/"
          TARGET: ${{ secrets.PATH }}
